theme: jekyll-theme-slate
title: Stardew Fishing Bot With Neural Network!
description: A python 3.6 program for a fully autonomous fishing bot. Work in progress.
text:It heavily depends on Opencv to understand what is happening in your screen, doing template matching and color detection to individually track the green rectangle and the little fish icon in real time. I am not a experienced programmer, so don’t expect a lot from this. The sole purpose of me posting this in GitHub is so someone can help me.
