# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 02:29
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180213_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='file',
            field=models.FileField(upload_to=data.models.user_directory_path),
        ),
    ]
