# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180222_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
