# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_userdata_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
