# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-12 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Dev', max_length=20),
        ),
    ]
